// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for RestartOperationResultStatus.
const (
	Restarted  RestartOperationResultStatus = "restarted"
	Restarting RestartOperationResultStatus = "restarting"
)

// Defines values for ServerStatusState.
const (
	Failed   ServerStatusState = "failed"
	Running  ServerStatusState = "running"
	Starting ServerStatusState = "starting"
	Stopped  ServerStatusState = "stopped"
	Stopping ServerStatusState = "stopping"
	Unknown  ServerStatusState = "unknown"
)

// Defines values for UpdateJobPhase.
const (
	UpdateJobPhaseBackingUp       UpdateJobPhase = "backing_up"
	UpdateJobPhaseChecking        UpdateJobPhase = "checking"
	UpdateJobPhaseCheckingStopped UpdateJobPhase = "checking_stopped"
	UpdateJobPhaseCompleted       UpdateJobPhase = "completed"
	UpdateJobPhaseQueued          UpdateJobPhase = "queued"
	UpdateJobPhaseStarting        UpdateJobPhase = "starting"
	UpdateJobPhaseStopping        UpdateJobPhase = "stopping"
	UpdateJobPhaseUpdating        UpdateJobPhase = "updating"
	UpdateJobPhaseVerifying       UpdateJobPhase = "verifying"
)

// Defines values for UpdateJobStatus.
const (
	UpdateJobStatusFailed      UpdateJobStatus = "failed"
	UpdateJobStatusInterrupted UpdateJobStatus = "interrupted"
	UpdateJobStatusQueued      UpdateJobStatus = "queued"
	UpdateJobStatusRunning     UpdateJobStatus = "running"
	UpdateJobStatusSucceeded   UpdateJobStatus = "succeeded"
)

// Defines values for UpdateJobRequestConfirmation.
const (
	UpdateJobRequestConfirmationUPDATESUZUME UpdateJobRequestConfirmation = "UPDATE SUZUME"
)

// Defines values for UpdatePlanBlockers.
const (
	ALREADYCURRENT UpdatePlanBlockers = "ALREADY_CURRENT"
	PLAYERSONLINE  UpdatePlanBlockers = "PLAYERS_ONLINE"
)

// Defines values for UpdatePlanConfirmation.
const (
	UpdatePlanConfirmationUPDATESUZUME UpdatePlanConfirmation = "UPDATE SUZUME"
)

// CommandResponse defines model for CommandResponse.
type CommandResponse struct {
	Data struct {
		Command    string  `json:"command"`
		Parameters *string `json:"parameters"`
		Result     string  `json:"result"`
	} `json:"data"`
	Meta struct {
		ServerTime *time.Time `json:"serverTime"`
	} `json:"meta"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string                  `json:"code"`
		Details *map[string]interface{} `json:"details,omitempty"`
		Message string                  `json:"message"`
	} `json:"error"`
}

// ExecResult defines model for ExecResult.
type ExecResult struct {
	Command    string    `json:"command"`
	DurationMs int       `json:"durationMs"`
	ExitCode   int       `json:"exitCode"`
	FinishedAt time.Time `json:"finishedAt"`
	Output     string    `json:"output"`
	StartedAt  time.Time `json:"startedAt"`
}

// OperationResult defines model for OperationResult.
type OperationResult struct {
	Exec   ExecResult `json:"exec"`
	Note   *string    `json:"note"`
	Status string     `json:"status"`
}

// RestartOperationResult defines model for RestartOperationResult.
type RestartOperationResult struct {
	Exec struct {
		Start ExecResult `json:"start"`
		Stop  ExecResult `json:"stop"`
	} `json:"exec"`
	Status RestartOperationResultStatus `json:"status"`
}

// RestartOperationResultStatus defines model for RestartOperationResult.Status.
type RestartOperationResultStatus string

// ServerStatus defines model for ServerStatus.
type ServerStatus struct {
	LastStartedAt *time.Time        `json:"lastStartedAt"`
	Notes         *string           `json:"notes,omitempty"`
	Pid           *int              `json:"pid"`
	ServiceName   string            `json:"serviceName"`
	State         ServerStatusState `json:"state"`
	UptimeSeconds *int              `json:"uptimeSeconds"`
}

// ServerStatusState defines model for ServerStatus.State.
type ServerStatusState string

// ServerSummary defines model for ServerSummary.
type ServerSummary struct {
	Data struct {
		Hostiles *[]SummaryHostile `json:"hostiles,omitempty"`
		Players  *[]SummaryPlayer  `json:"players,omitempty"`
		Stats    *struct {
			Animals  *int `json:"animals"`
			GameTime *struct {
				Days    *int `json:"days,omitempty"`
				Hours   *int `json:"hours,omitempty"`
				Minutes *int `json:"minutes,omitempty"`
			} `json:"gameTime,omitempty"`
			Hostiles      *int `json:"hostiles,omitempty"`
			PlayersOnline *int `json:"playersOnline,omitempty"`
		} `json:"stats,omitempty"`
		Status *ServerStatus `json:"status,omitempty"`
	} `json:"data"`
	Meta struct {
		Partial    *bool      `json:"partial,omitempty"`
		ServerTime *time.Time `json:"serverTime,omitempty"`
		Sources    *[]struct {
			Error     *string `json:"error"`
			LatencyMs *int    `json:"latencyMs"`
			Name      *string `json:"name,omitempty"`
			Ok        *bool   `json:"ok,omitempty"`
		} `json:"sources,omitempty"`
	} `json:"meta"`
}

// SummaryHostile defines model for SummaryHostile.
type SummaryHostile struct {
	Id       *int    `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Position *struct {
		X *float32 `json:"x,omitempty"`
		Y *float32 `json:"y,omitempty"`
		Z *float32 `json:"z,omitempty"`
	} `json:"position,omitempty"`
}

// SummaryPlayer defines model for SummaryPlayer.
type SummaryPlayer struct {
	Banned *struct {
		BanActive *bool      `json:"banActive,omitempty"`
		Reason    *string    `json:"reason"`
		Until     *time.Time `json:"until"`
	} `json:"banned"`
	CrossplatformId *struct {
		CombinedString *string `json:"combinedString,omitempty"`
		PlatformId     *string `json:"platformId,omitempty"`
		UserId         *string `json:"userId,omitempty"`
	} `json:"crossplatformId,omitempty"`
	Deaths   *int     `json:"deaths"`
	EntityId *int     `json:"entityId,omitempty"`
	Health   *float32 `json:"health"`
	Ip       *string  `json:"ip"`
	Kills    *struct {
		Players *int `json:"players,omitempty"`
		Zombies *int `json:"zombies,omitempty"`
	} `json:"kills"`
	Level      *int    `json:"level"`
	Name       *string `json:"name,omitempty"`
	Online     *bool   `json:"online,omitempty"`
	Ping       *int    `json:"ping"`
	PlatformId *struct {
		CombinedString *string `json:"combinedString,omitempty"`
		PlatformId     *string `json:"platformId,omitempty"`
		UserId         *string `json:"userId,omitempty"`
	} `json:"platformId,omitempty"`
	Position *struct {
		X *float32 `json:"x,omitempty"`
		Y *float32 `json:"y,omitempty"`
		Z *float32 `json:"z,omitempty"`
	} `json:"position"`
	Score   *int     `json:"score"`
	Stamina *float32 `json:"stamina"`
}

// UpdateJob defines model for UpdateJob.
type UpdateJob struct {
	BackupId       *string   `json:"backupId,omitempty"`
	CreatedAt      time.Time `json:"createdAt"`
	CurrentVersion string    `json:"currentVersion"`
	Error          *struct {
		Code    string                  `json:"code"`
		Details *map[string]interface{} `json:"details,omitempty"`
		Message string                  `json:"message"`
	} `json:"error,omitempty"`
	FinishedAt       *time.Time      `json:"finishedAt,omitempty"`
	JobId            string          `json:"jobId"`
	Phase            UpdateJobPhase  `json:"phase"`
	PlanId           string          `json:"planId"`
	RecoveryRequired bool            `json:"recoveryRequired"`
	ResultVersion    *string         `json:"resultVersion,omitempty"`
	Status           UpdateJobStatus `json:"status"`
	TargetVersion    string          `json:"targetVersion"`
	UpdatedAt        time.Time       `json:"updatedAt"`
}

// UpdateJobPhase defines model for UpdateJob.Phase.
type UpdateJobPhase string

// UpdateJobStatus defines model for UpdateJob.Status.
type UpdateJobStatus string

// UpdateJobRequest defines model for UpdateJobRequest.
type UpdateJobRequest struct {
	Confirmation   UpdateJobRequestConfirmation `json:"confirmation"`
	IdempotencyKey string                       `json:"idempotencyKey"`
	PlanId         string                       `json:"planId"`
}

// UpdateJobRequestConfirmation defines model for UpdateJobRequest.Confirmation.
type UpdateJobRequestConfirmation string

// UpdateJobResponse defines model for UpdateJobResponse.
type UpdateJobResponse struct {
	Data UpdateJob `json:"data"`
}

// UpdatePlan defines model for UpdatePlan.
type UpdatePlan struct {
	Blockers       []UpdatePlanBlockers   `json:"blockers"`
	CanExecute     bool                   `json:"canExecute"`
	Confirmation   UpdatePlanConfirmation `json:"confirmation"`
	CreatedAt      time.Time              `json:"createdAt"`
	CurrentVersion string                 `json:"currentVersion"`
	ExpiresAt      time.Time              `json:"expiresAt"`
	OnlinePlayers  int                    `json:"onlinePlayers"`
	PlanId         string                 `json:"planId"`
	Steps          []string               `json:"steps"`
	TargetVersion  string                 `json:"targetVersion"`
}

// UpdatePlanBlockers defines model for UpdatePlan.Blockers.
type UpdatePlanBlockers string

// UpdatePlanConfirmation defines model for UpdatePlan.Confirmation.
type UpdatePlanConfirmation string

// UpdatePlanResponse defines model for UpdatePlanResponse.
type UpdatePlanResponse struct {
	Data UpdatePlan `json:"data"`
}

// ExecServerCommandParams defines parameters for ExecServerCommand.
type ExecServerCommandParams struct {
	Command *string `form:"command,omitempty" json:"command,omitempty"`
}

// GetServerLogsParams defines parameters for GetServerLogs.
type GetServerLogsParams struct {
	Lines *int `form:"lines,omitempty" json:"lines,omitempty"`
}

// GetServerSummaryParams defines parameters for GetServerSummary.
type GetServerSummaryParams struct {
	IncludePositions *bool `form:"includePositions,omitempty" json:"includePositions,omitempty"`
	MaskIPs          *bool `form:"maskIPs,omitempty" json:"maskIPs,omitempty"`
	LimitHostiles    *int  `form:"limitHostiles,omitempty" json:"limitHostiles,omitempty"`
	TimeoutSeconds   *int  `form:"timeoutSeconds,omitempty" json:"timeoutSeconds,omitempty"`
	Verbose          *bool `form:"verbose,omitempty" json:"verbose,omitempty"`
}

// PlanServerUpdateJSONBody defines parameters for PlanServerUpdate.
type PlanServerUpdateJSONBody = map[string]interface{}

// CreateServerUpdateJobJSONRequestBody defines body for CreateServerUpdateJob for application/json ContentType.
type CreateServerUpdateJobJSONRequestBody = UpdateJobRequest

// PlanServerUpdateJSONRequestBody defines body for PlanServerUpdate for application/json ContentType.
type PlanServerUpdateJSONRequestBody = PlanServerUpdateJSONBody
